version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: solar-recorder-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - MODEL=${MODEL:-base}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
      - FORCE_CPU=true
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - solar-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: solar-recorder-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - solar-network

networks:
  solar-network:
    driver: bridge

volumes:
  uploads:
    driver: local