#!/bin/bash

# Solar Recorder v1.1.1 - QA Ready Build
# Automated Setup Script
# Created by Claude for AI | IT | Solar

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}"
echo "╔══════════════════════════════════════════════════════════╗"
echo "║                                                          ║"
echo "║         🛰  Solar Recorder v1.1.1 Installer             ║"
echo "║              QA Ready Build                              ║"
echo "║                                                          ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Check if Docker is installed
echo -e "${YELLOW}[1/6] Checking Docker installation...${NC}"
if ! command -v docker &> /dev/null; then
    echo -e "${RED}❌ Docker is not installed. Please install Docker first.${NC}"
    echo "Visit: https://docs.docker.com/get-docker/"
    exit 1
fi
echo -e "${GREEN}✅ Docker found: $(docker --version)${NC}"

# Check if Docker Compose is installed
echo -e "${YELLOW}[2/6] Checking Docker Compose installation...${NC}"
if ! command -v docker compose &> /dev/null; then
    echo -e "${RED}❌ Docker Compose is not installed.${NC}"
    exit 1
fi
echo -e "${GREEN}✅ Docker Compose found${NC}"

# Create necessary directories
echo -e "${YELLOW}[3/6] Creating directories...${NC}"
mkdir -p backend/uploads
mkdir -p backend/uploads/videos
mkdir -p backend/uploads/transcripts
mkdir -p backend/uploads/translations
mkdir -p backend/uploads/pdfs
echo -e "${GREEN}✅ Directories created${NC}"

# Create .env file if it doesn't exist
echo -e "${YELLOW}[4/6] Setting up environment variables...${NC}"
if [ ! -f backend/.env ]; then
    cat > backend/.env << EOF
# Solar Recorder Configuration
# Generated by setup.sh

# Whisper Model (tiny/base/small/medium/large)
MODEL=base

# DeepSeek API Key (optional - for translation feature)
DEEPSEEK_API_KEY=

# CORS Origins (comma-separated)
CORS_ORIGINS=http://localhost:3000

# Server Configuration
HOST=0.0.0.0
PORT=8000

# Upload Settings
MAX_FILE_SIZE=500MB
EOF
    echo -e "${GREEN}✅ Created backend/.env file${NC}"
    echo -e "${YELLOW}📝 Note: Edit backend/.env to add DEEPSEEK_API_KEY for translation feature${NC}"
else
    echo -e "${GREEN}✅ backend/.env already exists${NC}"
fi

# Stop any running containers
echo -e "${YELLOW}[5/6] Stopping existing containers...${NC}"
docker compose down 2>/dev/null || true
echo -e "${GREEN}✅ Cleanup complete${NC}"

# Build and start containers
echo -e "${YELLOW}[6/6] Building and starting containers...${NC}"
echo -e "${BLUE}This may take a few minutes on first run...${NC}"
docker compose up --build -d

# Wait for services to be ready
echo -e "${YELLOW}Waiting for services to start...${NC}"
sleep 5

# Check if services are running
if docker compose ps | grep -q "Up"; then
    echo -e "${GREEN}"
    echo "╔══════════════════════════════════════════════════════════╗"
    echo "║                                                          ║"
    echo "║         🚀 Solar Recorder is ready!                     ║"
    echo "║                                                          ║"
    echo "╚══════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    echo ""
    echo -e "${GREEN}✅ Frontend:${NC} http://localhost:3000"
    echo -e "${GREEN}✅ Backend API:${NC} http://localhost:8000"
    echo -e "${GREEN}✅ API Documentation:${NC} http://localhost:8000/docs"
    echo ""
    echo -e "${BLUE}Commands:${NC}"
    echo "  • View logs:        docker compose logs -f"
    echo "  • Stop services:    docker compose down"
    echo "  • Restart services: docker compose restart"
    echo ""
    echo -e "${YELLOW}📝 Next steps:${NC}"
    echo "  1. Open http://localhost:3000 in your browser"
    echo "  2. Click 'Start Recording' to test screen recording"
    echo "  3. Check 'Recordings Library' to view saved recordings"
    echo ""
    if [ -z "$(grep 'DEEPSEEK_API_KEY=.' backend/.env)" ]; then
        echo -e "${YELLOW}⚠️  Translation feature disabled (no DeepSeek API key)${NC}"
        echo "   To enable: edit backend/.env and add your DEEPSEEK_API_KEY"
        echo ""
    fi
else
    echo -e "${RED}❌ Failed to start services. Check logs with: docker compose logs${NC}"
    exit 1
fi